### PR TITLE
manage the serviceMonitor for ocm agent

### PR DESCRIPTION
**Pull request by bmeng**
### What type of PR is this?
_feature_

### What this PR does / why we need it?
Manage the servicemonitor which used by the ocm-agent to expose the metrics

### Which Jira/Github issue(s) this PR fixes?

_Fixes #OSD-10056_

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Ran `make generate` command locally to validate code changes
- [ ] Included documentation changes with PR

### CODE REVIEW

**Comment by mrbarge** [comment]
Encountered a couple of errors testing this on-cluster but I think they are all pretty straightforward to fix.

First it was erroring with this:
```
no kind is registered for the type v1.ServiceMonitor in scheme \"pkg/runtime/scheme.go:100
```

To fix, this requires a couple of things:

- Firstly the monitoringv1 API will need to be registered, this can happen in `main.go`, you can see an example where I've needed to do a similar thing in PR #23 but it will look a little like this:
```
	if err = monitoringv1.AddToScheme(mgr.GetScheme()); err != nil {
		log.Error(err, "")
		os.Exit(1)
	}
```

- Secondly the OCM Agent controller will need to watch for changes to `ServiceMonitor`, so something like this:

```
	err = c.Watch(&source.Kind{Type: &monitoringv1.ServiceMonitor{}}, &handler.EnqueueRequestForOwner{
		IsController: true,
		OwnerType:    &ocmagentv1alpha1.OcmAgent{},
	}, oaPredicate)
	if err != nil {
		return err
	}
```

The other thing that I think is missing is that the existing RBAC for ServiceMonitors (https://github.com/bmeng/ocm-agent-operator/blob/23091555090b4ea76d195f02c230b448db47db0e/deploy/20_ocm-agent-operator.Role.yaml#L45) needs to be updated, its current perms are of `get` and `list` are insufficient, it will need the full suite:

```
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
```

**Comment by bmeng** [comment]
New changes ready to review, the changes including:

- Addressed the unregistered scheme for serviceMonitor resource
- Update the label for ocm-agent-operator pod from `name=ocm-agent-operator` to `app=ocm-agent-operator` to match with the other services
- Update the old `oao-pullsecret-reader.Role` to `oao-openshiftconfig-reader.Role` to GET/WATCH/LIST several more resources which are needed for ocm agent operator.

**Comment by mrbarge** [comment]
I'll fix the outstanding issues in a separate PR.
/lgtm

**Pull request merged**
