### PR TITLE
Enable FIPS support for OAO

### PR DESCRIPTION
**Pull request by mrbarge**
### What type of PR is this?
Feature

### What this PR does / why we need it?

Boilerplate update that enables FIPs support for OAO.

---
https://github.com/openshift/boilerplate/compare/dcfe34f6135d3d22735eb5374a8fc31b4d4cca81...0a69514b0c6b0cec124afb603ae2fd2e02ec7fcd

commit: 8e0880fc695a2421cdd400249690a997ce50ff11
author: Antony Natale
changes source of operator name as it is not compatible with jenkins pipeline

commit: 9744d76fc22d4b838dadee9fb229f5e591e837ac
author: John Roche
Change to a template file

### Which Jira/Github issue(s) this PR fixes?

[OSD-11682](https://issues.redhat.com//browse/OSD-11682)

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Ran `make generate` command locally to validate code changes
- [ ] Included documentation changes with PR

### CODE REVIEW

**Comment by mrbarge** [comment]
@wanghaoran1988 did I do this PR right?

**Comment by wanghaoran1988** [comment]
@mrbarge yes, thanks for working on this.

**Pull request merged**
