### PR TITLE
build the service for metrics endpoint

### PR DESCRIPTION
**Pull request by bmeng**
### What type of PR is this?
_feature_

### What this PR does / why we need it?
build the service for metrics endpoint when the metrics is enabled for ocm-agent

### Which Jira/Github issue(s) this PR fixes?

_Fixes #OSD-10056_

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Ran `make generate` command locally to validate code changes
- [ ] Included documentation changes with PR

### CODE REVIEW

**Comment by mrbarge** [comment]
Good change, love the refactor of the service code. Tested it and it is working well.

The only thing to note is that it should also deploy a `ServiceMonitor` too, right?

**Comment by bmeng** [comment]
yeah, I think so, the serviceMonitor will be needed as well. 
So we should handle that in different go file right?

**Comment by mrbarge** [comment]
> yeah, I think so, the serviceMonitor will be needed as well. So we should handle that in different go file right?

I think so, yeah. Or it could go in alongside the `service` code since they are so coupled - not really opinionated on that one. 

I wonder if it might be easy to re-use the `createServiceMonitors` helper that the metrics package has, as used in `main.go`: https://github.com/openshift/ocm-agent-operator/blob/bb33542f6efadf2abebe2e0c034de590ec2b59c5/cmd/manager/main.go#L182

**Comment by bmeng** [comment]
hmm, if we can use this `addMetrics` function to create the serviceMonitor for ocm-agent, I think we can also use it to create the metrics service for ocm-agent?
But it looks a bit weird to me...

**Comment by mrbarge** [comment]
Given the ServiceMonitor will be done in #24, I'm happy to lgtm this now. Sooo..
/lgtm

**Pull request merged**
