### PR TITLE
prevent pdb create/delete if replicas count set to <=1

### PR DESCRIPTION
**Pull request by a7vicky**
### What type of PR is this?
Add logic to create/delete pdb only if the `ocm-agent` service replicas count is set to > 1.

### CODE REVIEW

**Comment by bmeng** [comment]
I was thinking this in the other PR https://github.com/openshift/ocm-agent-operator/pull/102/files#diff-963f34768705271107677c7d4999893fb35d1d52107e6029d2b934973385eb0fR29
But do we have a use case like this? The `ocmagent` CR should be deployed via cicd, which is configured in https://github.com/openshift/ocm-agent/pull/70/files

**Comment by xiaoyu74** [comment]
Thanks @a7vicky for adding the logic

The logic of this PR to check the count of replicas count of `ocm-agent` before creating PDB looks good. If you've tested against an actual cluster to verify it's all good, then LGTM :+1: 

Responding to @bmeng - I assume this [PR-70](https://github.com/openshift/ocm-agent/pull/70/files) is to define the replicas count of ocm-agent in Hive's `SelectorSyncSet` template, which will be then applied to the clusters via AppSRE's CI/CD ?

**Pull request merged**
