### PR TITLE
Adding ocm-agent-operator skeleton files

### PR DESCRIPTION
**Pull request by ravitri**
Based on Jira [OSD-8938](https://issues.redhat.com/browse/OSD-8938), adding skeleton files for ocm-agent-operator. 

Highlights:
1. operator initialized by operator-sdk 0.18.2
2. API version is `ocmagent.managed.openshift.io/v1alpha1` and CR is `OCMAgent`
3. Boilerplate is initialized to support default `make` commands
4. Controller-runtime version was changed from 0.6.0 to 0.10.0 (This lets the operator use more recent controller-runtime that's available in 1.x version of operator-sdk).
5. Kube dependencies pinned to 0.21 for now (same as in MUO).

Remarks:
1. If the CR name or the group name needs to be changed then we can do that. Alternative seems to be `OcmAgent`. 
2. CRD definitions can be updated as per [OSD-8937](https://issues.redhat.com/browse/OSD-8937) ahead.
3. operator-sdk version was chosen to be 0.18.2 based on work in [OSD-8935](https://issues.redhat.com/browse/OSD-8935) so far. 
4. All the `make` commands were tried and they ran fine. 
5. Operator startup seemed fine in local run.

### CODE REVIEW

**Comment by 2uasimojo** [comment]
It would be cool to get [prow set up](https://github.com/openshift/boilerplate/blob/master/boilerplate/openshift/golang-osd-operator/README.md#prow) for this repo in conjunction with this PR — that would validate the boilerplate setup better than a human reviewer could. It’s a bit chicken/egg — you’ll have to ignore the rehearsal failures in the release PR initially. Let me know if you need help.

**Comment by T0MASD** [comment]
I'm getting an error when running `make tools`:
```
verifying github.com/mikefarah/yaml/v2@v2.4.0/go.mod: checksum mismatch
	downloaded: h1:RDklbk79AGWmwhnvt/jBztapEOGDOx6ZbXqjP6csGnQ=
	go.sum:     h1:ahVqZF4n1W4NqwvVnZzC4es67xsW9uR/RRf2RRxieJU=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```

**Comment by ravitri** [comment]
@T0MASD - Can you run the following commands and share if it works?
```bash
GOPROXY=https://proxy.golang.org go get -d github.com/mikefarah/yaml/v2
go mod tidy
make tools
```
Basically, your GOPROXY might be set to "direct". The public checksum server agrees with the `h1:ahVqZF4n1W4NqwvVnZzC4es67xsW9uR/RRf2RRxieJU=` checksum, and GOPROXY=direct gives the `h1:RDklbk79AGWmwhnvt/jBztapEOGDOx6ZbXqjP6csGnQ=` checksum. So that suggests that the v2.4.0 tag was moved at some point after it was first read by the checksum server. Main point here is to set the GOPROXY variable and try again. Regards local configuration.

**Comment by T0MASD** [comment]
thanks for clarification @ravitri I've cleaned up my env, built the tools and ran make, no errors here. Other than suggested change lgtm from me

**Pull request merged**
