### PR TITLE
Adding PR template

### PR DESCRIPTION
**Pull request by ravitri**
Adding PR template

### CODE REVIEW

**Comment by georgettica** [comment]
should this be standard for all operators?

**Comment by ravitri** [comment]
The template is the same that we have been using for MUO so far and its been helpful to structure some points for the reviewers to get quick context of the PR. Though this is not specific to operator repos, having a default/standard PR template across the repos would be helpful I think. Am not sure if the solution for it should come from boilerplate or openshift org or some other way.

**Comment by georgettica** [comment]
I'll leave it to the team leads to decide, but will for now add a PR in the repo's orange is currently owning with some changes

**Comment by georgettica** [comment]
@ravitri `make generate` doesn't exist here

if you want to verify people will run the command, you can write a simple action that 
1. checkouts the code
2. runs `make generate`
3. verifies git diff is clean

if you want I can create a PR for this in MUO

**Comment by ravitri** [comment]
Yes, so far it doesn't exist. I have another PR almost ready which has it for this repo. Will raise the PR tomorrow mostly. For MUO, yes that seems good to have. Meanwhile, do go ahead and raise a PR against MUO repo. We'll add it to this repo too then.

**Pull request merged**
